spring.application.name=inventory

# PostgreSQL connection
spring.datasource.url=jdbc:postgresql://localhost:5432/philadelphia_inventory
spring.datasource.username=postgres
spring.datasource.password=${DB_PASSWORD}

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.open-in-view=false